name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create token key file from GitHub Secret
        run: echo "${{ secrets.TOKEN_KEY_CONTENTS }}" > AuthKey_FNA4AUV8ML.p8

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          - name: Log in to AWS ECR
          run: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set region ${{ secrets.AWS_REGION }}
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin \
            $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        run: |
          docker build --build-arg TOKEN_KEY_FILE=AuthKey_FNA4AUV8ML.p8 -t "${{ secrets.DOCKER_USERNAME }}"/personal:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/personal:latest \
          $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.DOCKER_USERNAME }}/personal:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}"/personal:latest
        
      - name: Push Docker image to AWS ECR
        run: |
            docker push $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.DOCKER_USERNAME }}/personal:latest